% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/scraping.R
\name{download_epaPM}
\alias{download_epaPM}
\title{Downloads the PM data from the EPA}
\usage{
download_epaPM(
  remDr,
  states = c("Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado",
    "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois",
    "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland",
    "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana",
    "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York",
    "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania",
    "Rhode Island", "South Carolina", "South Dakota",      "Tennessee", "Texas", "Utah",
    "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"),
  shorts = c("al", "ak", "az", "ar", "ca", "co", "ct", "de", "fl", "ga", "hi", "id",
    "il", "in", "ia", "ks", "ky", "la", "me", "md", "ma", "mi", "mn", "ms", "mo", "mt",
    "ne", "nv", "nh", "nj", "nm", "ny", "nc", "nd", "oh", "ok", "or", "pa", "ri", "sc",
    "sd", "tn", "tx", "ut", "vt", "va", "wa", "wv", "wi", "wy"),
  years,
  path = "~/BurkeLab Dropbox/Projects/wildfire/data/pm25/epa/",
  url = "https://www.epa.gov/outdoor-air-quality-data/download-daily-data",
  pollutant = "\\"88101','88502\\""
)
}
\arguments{
\item{remDr}{the RSelenium driver, example below}

\item{states}{a vector of the state names you want to pull. Eg c("Alabama", "New York")}

\item{shorts}{a vector of the two letter version of states. Eg c("al", "ny")}

\item{years}{a vector of years of interest. Eg 2012:2018}
}
\description{
Requires RSelenium, which has some setup cost. You will need to download the Java developer kit, as well as geckodriver. 
There are some reports that the most recent geckodriver is causing some issues so I recommend using: rD <- rsDriver(geckover="0.23.0") 
to create your driver. Becuase I built this haphazardly, it will throw errors while running, if it's a 'Unable to locate element', it's probably 
fine, it's just checking for errors. You also either need the chrome 77 development build or firefox.
JDK: https://www.oracle.com/technetwork/java/javase/downloads/jdk12-downloads-5295953.html
}
\examples{
rD <- rsDriver(geckover="0.23.0")
remDr <- rD[["client"]]
download_epaPM(remDr, c("Alabama", "New York"), c("al", "ny"), 2006:2008)
pollutant="\"42602\"" is for NO2
}