library(RCurl)
library(R.utils)
library(XML)
library(rvest)
library(rlang)
library(ff)

library(tigris)
library(tidycensus)
library(rgee)

library(splitr)

library(tools)
library(readr)
library(readxl)
library(retry)

library(stringr)
library(lubridate)

library(parallel)
library(foreach)
library(doParallel)

library(FNN)
library(sp)
library(sf) # Linking to GEOS 3.9.1, GDAL 3.3.1, PROJ 8.1.0
library(ncdf4)
library(raster)
library(rgdal)
library(rgeos)
library(SpatialPosition)
library(exactextractr)

library(magrittr)
library(tibble)
library(plyr)
library(dplyr)
library(tidyr)
library(purrr)

import::from(data.table, .except = c("hour", "month", "wday", "week", "year"))
library(gtable)
library(fixest)
library(splines)
library(matrixStats)

library(xgboost)
library(rBayesianOptimization)

library(ggplot2)
library(ggpubr)
library(grid)
library(gridExtra)
library(cowplot)
library(scales)
library(RColorBrewer)
library(layer)
library(facetscales)
library(DiagrammeR)
library(DiagrammeRsvg)
library(rsvg)
